apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yof5pw4at-python 
  janus-idp.io/tekton: yof5pw4at-python
  backstage.io/kubernetes-id: yof5pw4at-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yof5pw4at-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  