apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yof5pw4at-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yof5pw4at-python 
  name: yof5pw4at-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yof5pw4at-python 
